version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    #links:
    #  - "db:redis"
    networks:
      - spring
  redis:
    image: 'redis:alpine'
    hostname:
      redis
    ports:
      - "6379:6379"
    networks:
      - spring
  mockServer:
    image: mockserver/mockserver:mockserver-5.11.1
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
    volumes:
      - type: bind
        source: .
        target: /config
networks:
  spring:
#    external:
#      name: spring
    #driver: bridge
