version: '3'
services:
  app:
    build:
      context: .
    container_name: flight_information_app
    ports:
      - 8080:8080
    networks:
      - spring
  redis:
    image: 'redis:alpine'
    container_name: flight_information_redis
    ports:
      - 6379:6379
    networks:
      - spring
  mockServer:
    image: mockserver/mockserver:mockserver-5.11.1
    container_name: mock-server
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
    volumes:
      - type: bind
        source: .
        target: /config
    networks:
      - spring
networks:
  spring:
    driver: "bridge"